Introduce dmsg Tests fs10 with corrupt data
RFD-FHEM/RFFHEM pull request #1034
Opened 2021-11-16 22:17 UTC by sidey79

* **Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added / modified (needed for for bug fixes / features)
- [ ] commandref has been added / updated (needed for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix (please link issue)
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Unittest enhancement
- [ ] other

* **What is the current behavior?** 
(You can also link to an open issue here, if this describes the current behavior)

Coverage decreases for some code parts due to changed regex in #1033 

* **What is the new behavior (if this is a feature change)?**

FS10 Module is also tested with currupt data to test some more code paths
There is also a test module introduced, which saves repeating steps performing a dmsg test for modules

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no 

* **Other information**:

2021-11-18 11:42 UTC, HomeAutoUser submitted a review, later dismissed

2021-11-18 15:55 UTC, elektron-bbs requested changes

2021-11-18 15:55 UTC, elektron-bbs commented on FHEM/10_FS10.pm
> +		return ;
Bitte diese Änderungen rückgängig machen, sonst füllt es den Usern das Log mit solchen Ausgaben:

```
2021.11.17 10:31:06 3: sduinoUSB0: Unknown code P61#06C2C3805F, help me!
2021.11.17 10:31:07 3: sduinoIP: Unknown code P61#06C2C3804, help me!
2021.11.17 10:34:26 3: sduinoUSB0: Unknown code P61#09C2308286, help me!
2021.11.17 10:37:45 3: sduinoACM: Unknown code P61#7858901E2, help me!
2021.11.17 10:37:45 3: sduinoACM: Unknown code P61#06C2C480F1, help me!
2021.11.17 10:37:46 3: sduinoACM: Unknown code P61#09C2318272, help me!
2021.11.17 10:37:47 3: sduinoIP: Unknown code P61#2708C609, help me!
2021.11.17 10:41:04 3: sduinoACM: Unknown code P61#2309243B88, help me!
2021.11.17 10:41:05 3: sduinoACM: Unknown code P61#184921DC4, help me!
```

2021-11-18 15:57 UTC, elektron-bbs commented
Evtl. ist mein Einspruch ja untergegangen, deshalb nochmal: https://github.com/RFD-FHEM/RFFHEM/pull/1034#discussion_r752382979

2021-11-18 22:12 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
Hmm, das Problem ist, dass vorher ein Wert zurück gegeben wurde.
ParseFN soll aber nur den Devicenamen liefern, wenn eine Definition zugeordnet wurde.

So sieht der Aufruf in den aus:
`my @tfound = &{$modules{$mname}{ParseFn}}($hash,$dmsg);`

Anhand der Rückgabe wird entweder nach weiteren Modulen gesucht, die etwas damit anfangen können oder nicht.

Ich habe hier auf undef geändert, weil es keine Definition mit dem Wert von Empty gibt, dieser aber wie eine erfolgreiche Verarbeitung gewertet wird.

Das war zunächst der einfachste und stimmigste Weg für mich.
Selbst wenn wir [NEXT] zurück geben erscheint mir das seltsam.

Über einen Weiteren Parameter im Dispatch aufrufs kann das Verhalten wohl auch beeinflusst werden, aber immer will man es ja wohl nicht abstellen oder?

2021-11-19 19:53 UTC, elektron-bbs commented on FHEM/10_FS10.pm
> +		return ;
> Hmm, das Problem ist, dass vorher ein Wert zurück gegeben wurde. ParseFN soll aber nur den Devicenamen liefern, wenn eine Definition zugeordnet wurde.

Naja, den Devicenamen offensichtlich nur, wenn es erfolgreich geparst wurde, denn es gibt noch eine weitere Variante, die nirgends dokumentiert ist...

> So sieht der Aufruf in den aus: `my @tfound = &{$modules{$mname}{ParseFn}}($hash,$dmsg);`

... einige Zeilen darunter:

```
  # Special return: Do not notify
  return undef if(!defined($found[0]) || $found[0] eq "");
```
 
> Ich habe hier auf undef geändert, weil es keine Definition mit dem Wert von Empty gibt, dieser aber wie eine erfolgreiche Verarbeitung gewertet wird.

Ich fand es auch etwas merkwürdig, erst eine Variable $EMPTY zu deklarieren, aber perlcritic empfiehlt es so:

https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitEmptyQuotes

```
    $message = '';      #not ok
    $message = "";      #not ok
    $message = "     "; #not ok
	
    $message = q{};     #better
    $message = q{     } #better
	
    $EMPTY = q{};
    $message = $EMPTY;      #best
    $SPACE = q{ };
    $message = $SPACE x 5;  #best
```

> Das war zunächst der einfachste und stimmigste Weg für mich. Selbst wenn wir [NEXT] zurück geben erscheint mir das seltsam.

Das habe ich noch nicht probiert, was dann passiert.

> Über einen Weiteren Parameter im Dispatch aufrufs kann das Verhalten wohl auch beeinflusst werden, aber immer will man es ja wohl nicht abstellen oder?

Ich denke, so wie es war, ist die beste Lösung, da auch Rudolf Koenig es in seinen Modulen, wie z.B. 14_CUL_WS.pm, 14_CUL_TX.pm, 10_FS20.pm usw. es so handhabt.

2021-11-20 19:50 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
Hmm, wieso nicht [NEXT]

Ich werde mal schauen was ich mit $EMPTY machen kann, aber $NEXT wäre meiner Ansicht nicht falscher.

2021-11-20 22:42 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
ich habe es wieder angepasst

2021-11-20 22:46 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
ich habe es auf empty zurück geändert

2021-11-21 09:53 UTC, elektron-bbs commented on FHEM/10_FS10.pm
> +		return ;
Zwei Stellen müsstest du noch wiederherstellen: Zeile 337 und 341

2021-11-21 10:24 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
Ich finde dazu kein Kommentar. Ist denn 309 jetzt so wie es sein soll?

2021-11-21 11:00 UTC, elektron-bbs commented
Zeile 303 und 309 sind OK.

2021-11-21 11:00 UTC, elektron-bbs requested changes

2021-11-21 15:51 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
okay, passe ich an. Ich ging davon aus, hier kann es bleiben wie ich es vorgeschlagen habe :)

2021-11-21 15:51 UTC, sidey79 commented on FHEM/10_FS10.pm
> +		return ;
okay, passe ich an. Ich ging davon aus, hier kann es bleiben wie ich es vorgeschlagen habe :)

2021-11-21 16:36 UTC, elektron-bbs submitted a review, later dismissed

2021-11-21 19:21 UTC, sidey79 commented
Ich habe noch Konflikte beseitigt, jetzt sollte es passen

2021-11-21 19:44 UTC, elektron-bbs approved these changes

2021-11-21 20:18 UTC, merged