New elements for attribute hardware
RFD-FHEM/RFFHEM pull request #1172
Opened 2023-04-29 18:39 UTC by sidey79

- updated Hardwarelist

* **Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added / modified (needed for for bug fixes / features)
- [ ] commandref has been added / updated (needed for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix (please link issue)
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Unittest enhancement
- [x] other

* **What is the current behavior?** 
(You can also link to an open issue here, if this describes the current behavior)

Hardware for esp32 and esp8266 does not guarantee, that it will load the right firmware, because the hardware name is searched in the filename.

* **What is the new behavior (if this is a feature change)?**

Hardware names without cc1101 have a suffix s which makes them uniqe 
Hardware names are also adapted to be compatible with https://github.com/RFD-FHEM/SIGNALDuino/pull/278

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

yes, the following hardware attribute are renamed 
esp32 to esp32s
esp8266 to esp8266s
promini  is removed and replaces with 
promini8cc1101
promini16cc1101
promini8s
promini16s

* **Other information**:

2023-04-30 08:59 UTC, elektron-bbs commented
Mhmm, muss das mit dem angehangen "s" unbedingt sein? Müssen dann alle User das Attribut ändern?

Außerdem gibt es noch etliche Differenzen zwischen Attribut, Dateiname und commandref. Das müsstest du dir nochmal genauer ansehen. Hier nur einige Beispiele:

```
nano328
SIGNALduino_nano328s_3.5.1.hex
nano328

ESP32s
SIGNALduino_esp32s_3.5.1.bin
ESP32d

ESP8266s
SIGNALduino_esp8266s_3.5.1.bin
ESP8266d
```

Vielleicht auch noch Groß-/Kleinschreibung vereinheitlichen, z.B. cc1101 vs. CC1101?

2023-04-30 10:01 UTC, sidey79 commented
> Mhmm, muss das mit dem angehangen "s" unbedingt sein? Müssen dann alle User das Attribut ändern

Ich sehe da aktuell keine einfache Alternative um eine Firmware eindeutig zu identifizieren. Betrifft hauptsächlich die ESPs welche sich ohnehin derzeit nicht über das Modul updaten lassen.

> Außerdem gibt es noch etliche Differenzen zwischen Attribut, Dateiname und commandref. Das müsstest du dir nochmal genauer ansehen. Hier nur einige Beispiele:

> ```
> nano328
> SIGNALduino_nano328s_3.5.1.hex
> nano328
> ```

Da nano328 bereits eindeutig ist, können wir dies so belassen. Es erspart den Anwendern das Anpassen ihres Attributen.

> ```
> ESP32s
> SIGNALduino_esp32s_3.5.1.bin
> ESP32d
> ```

Ich finde kein ESP32d. 

> ```
> ESP8266s
> SIGNALduino_esp8266s_3.5.1.bin
> ESP8266d
> ```


> Vielleicht auch noch Groß-/Kleinschreibung vereinheitlichen, z.B. cc1101 vs. CC1101?

Das würde zu weiteren Änderungen der Attribute führen. Bei der Suche nach der Firmware spielt groß/kleinschreibung keine Rolle.

2023-04-30 11:14 UTC, elektron-bbs requested changes

2023-04-30 11:14 UTC, elektron-bbs commented on FHEM/00_SIGNALduino.pm
> +      <li>ESP32d: ESP32 f&uuml;r einfachen eindraht Empf&auml;nger</li>
ESP32d - ESP32s

2023-04-30 11:14 UTC, elektron-bbs commented on FHEM/00_SIGNALduino.pm
> +      <li>ESP8266d: ESP8266 f&uuml;r einfachen eindraht Empf&auml;nger</li>
ESP8266d - ESP8266s

2023-05-01 09:20 UTC, elektron-bbs approved these changes

2023-05-01 10:08 UTC, merged